version: "3.8"

services:
  email-sender-api:
    container_name: 'email-sender-api'
    build:
      dockerfile: EmailSender.Api\Dockerfile
      context: .
    ports:
      - 5005:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Debug
      - LOGS_PATH=/var/log/dev-email-sender
      - SendGridOptions__SendGridAPIKey=***secret***
      - SendGridOptions__SenderEmail=***secret***
      - SendGridOptions__SenderName=***secret***
    networks:
      - ic-backend-deb

networks:
  ic-backend-deb:
    external: true
