{{ if .Values.deploySecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "chart.fullname" . }}-secret
type: Opaque
data:
  MailOptions__SenderMailAddress: {{ required "MailOptions.SenderMailAddress must be defined!" .Values.MailOptions.SenderMailAddress | b64enc | quote }}
  MailOptions__SenderMailPassword: {{ required "MailOptions.SenderMailPassword must be defined!" .Values.MailOptions.SenderMailPassword | b64enc | quote }}
{{ end }}
