name: deploy service to dev k8s

on:
  push:
    branches:
      - develop
  pull_request:

env:
  GITHUB_REGISTRY: ghcr.io

jobs:
  build-image:
    name: Build and push service image  
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: Build and push image
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
          docker build -t $GITHUB_REGISTRY/tourmalinecore/inner-circle/emailsender-service-api:latest -t $GITHUB_REGISTRY/tourmalinecore/inner-circle/emailsender-service-api:${{ github.sha }} -f EmailSender.Api/Dockerfile .
          docker push $GITHUB_REGISTRY/tourmalinecore/inner-circle/emailsender-service-api:latest
          docker push $GITHUB_REGISTRY/tourmalinecore/inner-circle/emailsender-service-api:${{ github.sha }}

  deploy-to-dev-k8s:
    needs: build-image
    name: Deploy service to k8s for development environment  
    if: github.event_name == 'push'
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: Deploy
        uses: WyriHaximus/github-action-helm3@v2
        with:
            # Disable ingress until resolve security issues
            # --set "ingress.hostname=${{ secrets.DEV_HOST }}" \
            # --set "ingress.enabled=true" \
          exec: |
            RELEASE_NAME=emailsender-service-api
            helm repo add bitnami https://charts.bitnami.com/bitnami
            helm upgrade --install --namespace dev-inner-circle --create-namespace --values ./EmailSender.Api/ci/values-custom.yaml \
            --set "image.tag=${{ github.sha }}" \
            --set "extraSecretEnvVars.GoogleSmtpOptions__Host=${{ secrets.DEV_MAIL_HOST }}" \
            --set "extraSecretEnvVars.GoogleSmtpOptions__Port=${{ secrets.DEV_MAIL_PORT }}" \
            --set "extraSecretEnvVars.GoogleSmtpOptions__FromEmail=${{ secrets.DEV_MAIL_FROM_EMAIL }}" \
            --set "extraSecretEnvVars.GoogleSmtpOptions__FromPassword=${{ secrets.DEV_MAIL_FROM_PASSWORD }}" \
            "${RELEASE_NAME}" \
            bitnami/aspnet-core
          kubeconfig: "${{ secrets.DEV_KUBECONFIG }}"


